### ISSUE TITLE
IC2 Water Mill recipe busted

### ISSUE THREAD

**Issue by joshgayou** [mmelvin0/Modpack#7]
If you "R" the water mill in NEI, nothing comes up.  Crafting it doesn't work either.  Laying the generator, sticks, and planks in the grid in the normal arrangement yields nothing in the output slot.

**Comment by mmelvin0** [comment]
Actually not a bug. The water mill was replaced with the Kinetic Water Generator. I think existing ones in the world still work (maybe :) but the recipe is gone and the machine itself is deprecated:

http://wiki.industrial-craft.net/index.php?title=Kinetic_Water_Generator

**Comment by joshgayou** [comment]
Crap.  What a waste of iron.
